### ISSUE TITLE
smmap and smmap2 on PyPI

### ISSUE THREAD

**Issue by Harmon758** [gitpython-developers/smmap#44]
In 2015, [access was lost to the PyPI account](https://github.com/gitpython-developers/GitPython/issues/298) that owns [smmap](https://pypi.org/project/smmap/).
v0.9.0 was the last release under the smmap package on PyPI prior to this happening.

In 2016, [smmap2](https://pypi.org/project/smmap2/) [was created to continue development for the library under a new package](https://github.com/gitpython-developers/GitPython/issues/511) (https://github.com/gitpython-developers/smmap/commit/09023b1013e081755dca575f62c35eb93ee8065a), and every release since then has been with that package name. This has caused confusion (see #42 and #43) and having an old, stale PyPI project is less than ideal.

[Recently, the original PyPI account has been recovered](https://github.com/pypa/pypi-support/issues/204).
The intention now is to transition back to using the original smmap package name and have the smmap2 package simply be a mirror/dummy package that depends on and installs smmap, so as to maintain backwards compatibility.

Currently, these are the anticipated steps that need to be taken:
- [x] ~~Release a new version of GitDB, v3.0.3, as the gitdb2 package, to restrict the smmap2 version to < 3 (https://github.com/gitpython-developers/gitdb/issues/59)~~
- [x] ~~Release a new version, v3.0.0, as the smmap package~~
- [x] ~~Create a smmap2 branch with a single setup.py that requires smmap~~
- [x] ~~Release a new version, v3.0.0, of the smmap2 package from the smmap2 branch~~
- [x] ~~Release a new version of GitDB, v4.0.0, as the gitdb package, that requires smmap rather than smmap2 (See https://github.com/gitpython-developers/gitdb/issues/59)~~

~~v3.0.0 for both packages should be functionally equivalent to smmap2 v2.0.5, with smmap2 v3.0.0 simply installing smmap >= 3.0.0.~~

- [X] gitdb2 v3.0.3 was released with an erroneous and incomplete changelog
gitdb2 v3.0.3.post1 has been [tagged](https://github.com/gitpython-developers/gitdb/releases/tag/3.0.3.post1) and [released on PyPI](https://pypi.org/project/gitdb2/3.0.3.post1/) to fix this
(https://github.com/gitpython-developers/gitdb/issues/59)
- [X] smmap v3.0.0 was released without a changelog
smmap v3.0.1 has been [tagged](https://github.com/gitpython-developers/smmap/releases/tag/v3.0.1) and [released on PyPI](https://pypi.org/project/smmap/3.0.1/) to fix this
- [X] smmap2 branch improperly branches off of master and includes the entire smmap library
The smmap2 branch has been force-pushed to https://github.com/gitpython-developers/smmap/commit/2422b9857c4dadc52bfafceedbea534640601b95 to be properly set up for smmap2 to be a mirror package and the smmap2-v3.0.0 tag has been deleted
- [X] smmap2 v3.0.0 was released as the entire smmap library while still requiring smmap
smmap2 v3.0.1 has been [released on PyPI](https://pypi.org/project/smmap2/3.0.1/) from the new smmap2 branch (https://github.com/gitpython-developers/smmap/commit/2422b9857c4dadc52bfafceedbea534640601b95)
  - [X] smmap2 v3.0.0 has been deleted on PyPI
- [X] A new version of GitDB, v4.0.1, has been [tagged](https://github.com/gitpython-developers/gitdb/releases/tag/4.0.1) and [released on PyPI](https://pypi.org/project/gitdb/4.0.1/ ) as the gitdb package, requiring smmap rather than smmap2 (See https://github.com/gitpython-developers/gitdb/issues/59)

v3.0.1 for both packages should be functionally equivalent to smmap2 v2.0.5, with smmap2 v3.0.1 simply installing smmap >= 3.0.1.

Note: @Byron was having issues with releases, so I was added as a maintainer for gitdb, gitdb2, smmap, and smmap2 on PyPI. Since [there were already issues with the new signature key being used](https://github.com/gitpython-developers/gitdb/issues/55), I've released gitdb v4.0.1, gitdb2 v3.0.3.post1, gitdb2 v4.0.2, smmap v3.0.1, and smmap2 v3.0.1 without any signature keys. The intention is still for @Byron to release new versions with the proper signature key once he has access to it again.

**Comment by Byron** [comment]
@Harmon758 Please close this issue if you believe the ACs are fulfilled. Thank you - and thanks for setting up the instructions in the first place - couldn't have done it without you!
